version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "20:00"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
